spring.application.name=GymTracker
spring.datasource.url=jdbc:postgresql://localhost:5432/gymtracker
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always

